openapi: 3.0.3
info:
  title: ProductAPI
  description: ''
  version: 1.0.0
servers:
  - url: 'http://localhost'
tags:
  - name: 'Account API Resource'
    description: ''
  - name: Authentication
    description: ''
  - name: Endpoints
    description: ''
  - name: 'Product API Resource'
    description: ''
  - name: 'User API Resource'
    description: ''
paths:
  /api/v1/accounts:
    get:
      summary: 'List all accounts'
      operationId: listAllAccounts
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Account API Resource'
      security: []
    post:
      summary: 'Create a new account'
      operationId: createANewAccount
      description: ''
      parameters: []
      responses: {}
      tags:
        - 'Account API Resource'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: fpcyimrlttwstgsfejhp
                account_number:
                  type: string
                  description: 'Must be between 2 and 10 digits.'
                  example: '793429968'
                status:
                  type: string
                  description: ''
                  example: active
                  enum:
                    - active
                    - pending
                    - disabled
              required:
                - name
                - account_number
                - status
      security: []
  '/api/v1/accounts/{id}':
    get:
      summary: 'View a account'
      operationId: viewAAccount
      description: 'Display a individual account data.'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Account API Resource'
      security: []
    put:
      summary: 'Update a account'
      operationId: updateAAccount
      description: 'Update the specified account'
      parameters: []
      responses: {}
      tags:
        - 'Account API Resource'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: aulz
                account_number:
                  type: string
                  description: 'Must be between 2 and 10 digits.'
                  example: '63099462'
                status:
                  type: string
                  description: ''
                  example: active
                  enum:
                    - active
                    - pending
                    - disabled
      security: []
    delete:
      summary: 'Delete a account.'
      operationId: deleteAAccount
      description: 'Remove the account resource'
      parameters: []
      responses: {}
      tags:
        - 'Account API Resource'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the account.'
        example: 1
        required: true
        schema:
          type: integer
  /api/token:
    post:
      summary: 'Get access token for a user'
      operationId: getAccessTokenForAUser
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n{\n  \"success\": {\n     \"token\": \"{YOUR_AUTH_KEY}\"\n}\n}"
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: gerda86@example.org
                password:
                  type: string
                  description: 'Must be at least 6 characters. Must not be greater than 255 characters.'
                  example: lF$yH|0
              required:
                - email
                - password
      security: []
  /api/me:
    get:
      summary: ''
      operationId: getApiMe
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/v1/accounts/{account_id}/price/{product_id}':
    patch:
      summary: ''
      operationId: patchApiV1AccountsAccount_idPriceProduct_id
      description: ''
      parameters: []
      responses: {}
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: number
                  description: ''
                  example: 69.28
              required:
                - price
      security: []
    parameters:
      -
        in: path
        name: account_id
        description: 'The ID of the account.'
        example: 1
        required: true
        schema:
          type: integer
      -
        in: path
        name: product_id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
  /api/v1/products:
    get:
      summary: 'List all products'
      operationId: listAllProducts
      description: ''
      parameters:
        -
          in: query
          name: sort
          description: 'by product name, status, published date, created date and updated date'
          example: expedita
          required: false
          schema:
            type: string
            description: 'by product name, status, published date, created date and updated date'
            example: expedita
        -
          in: query
          name: 'filter[status]'
          description: 'Filter by status: active,inactive,pending'
          example: repellat
          required: false
          schema:
            type: string
            description: 'Filter by status: active,inactive,pending'
            example: repellat
        -
          in: query
          name: 'filter[sku]'
          description: 'Filter by sku: 45117459,74569441'
          example: architecto
          required: false
          schema:
            type: string
            description: 'Filter by sku: 45117459,74569441'
            example: architecto
        -
          in: query
          name: 'filter[name]'
          description: 'Filter by name. Wildcards are supported.'
          example: '*fix*'
          required: false
          schema:
            type: string
            description: 'Filter by name. Wildcards are supported.'
            example: '*fix*'
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Product API Resource'
      security: []
    post:
      summary: 'Create a new product'
      operationId: createANewProduct
      description: ''
      parameters: []
      responses: {}
      tags:
        - 'Product API Resource'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 255 characters.'
                  example: kyitavonoinwfnolzzqfuekxm
                description:
                  type: string
                  description: 'Must be at least 10 characters. Must not be greater than 1000 characters.'
                  example: 'Dolor corrupti aut rem harum.'
                price:
                  type: number
                  description: ''
                  example: 0.0
                category_id:
                  type: integer
                  description: ''
                  example: 2
                  nullable: true
                sku:
                  type: string
                  description: 'Must match the regex /^[A-Z0-9]{4,25}$/.'
                  example: NTUBY
                barcode:
                  type: string
                  description: 'Must not be greater than 50 characters.'
                  example: spjqlfujvwzpcvvgudsoiyvj
                stock:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 72
                status:
                  type: string
                  description: ''
                  example: active
                  enum:
                    - active
                    - inactive
                    - pending
                    - disabled
                published_at:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2026-08-29T17:16:53'
              required:
                - name
                - description
                - price
                - sku
                - barcode
      security: []
  '/api/v1/products/{id}':
    get:
      summary: 'View a product'
      operationId: viewAProduct
      description: 'Display a individual product data.'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Product API Resource'
      security: []
    delete:
      summary: 'Delete a product.'
      operationId: deleteAProduct
      description: 'Remove the product resource'
      parameters: []
      responses: {}
      tags:
        - 'Product API Resource'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
  /api/v1/users:
    get:
      summary: 'List all users'
      operationId: listAllUsers
      description: ''
      parameters:
        -
          in: query
          name: sort
          description: 'by user name and email'
          example: excepturi
          required: false
          schema:
            type: string
            description: 'by user name and email'
            example: excepturi
        -
          in: query
          name: 'filter[name]'
          description: 'Filter by name. Wildcards are supported.'
          example: '*fix*'
          required: false
          schema:
            type: string
            description: 'Filter by name. Wildcards are supported.'
            example: '*fix*'
        -
          in: query
          name: 'filter[email]'
          description: 'Filter by email. Wildcards are supported.'
          example: '*fix*'
          required: false
          schema:
            type: string
            description: 'Filter by email. Wildcards are supported.'
            example: '*fix*'
        -
          in: query
          name: 'filter[role]'
          description: 'Filter by role. Wildcards are NOT supported.'
          example: 0
          required: false
          schema:
            type: integer
            description: 'Filter by role. Wildcards are NOT supported.'
            example: 0
        -
          in: query
          name: 'filter[account]'
          description: 'Filter by account. Wildcards are NOT supported.'
          example: 1
          required: false
          schema:
            type: integer
            description: 'Filter by account. Wildcards are NOT supported.'
            example: 1
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'User API Resource'
      security: []
    post:
      summary: 'Create a new user'
      operationId: createANewUser
      description: ''
      parameters: []
      responses: {}
      tags:
        - 'User API Resource'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: jimxdwmafhzlaylmcdytq
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: annette08@example.com
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: "tJ}3Zld'W8dG(Q7v"
                role:
                  type: string
                  description: ''
                  example: 'Account User'
                  enum:
                    - Admin
                    - 'Account Admin'
                    - 'Account User'
                    - 'Account Api User'
                account_id:
                  type: string
                  description: 'Must match an existing stored value.'
                  example: sed
              required:
                - name
                - email
                - password
                - role
                - account_id
      security: []
  '/api/v1/users/{id}':
    get:
      summary: 'View an user'
      operationId: viewAnUser
      description: 'Display an user with relational data.'
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'User API Resource'
      security: []
    put:
      summary: 'Update a user'
      operationId: updateAUser
      description: 'Update the specified user'
      parameters: []
      responses: {}
      tags:
        - 'User API Resource'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: bzuay
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: janice83@example.org
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: 'AJ&2fuM7)'
                role:
                  type: string
                  description: ''
                  example: 'Account User'
                  enum:
                    - Admin
                    - 'Account Admin'
                    - 'Account User'
                    - 'Account Api User'
      security: []
    delete:
      summary: 'Delete a user.'
      operationId: deleteAUser
      description: 'Remove the user resource'
      parameters: []
      responses: {}
      tags:
        - 'User API Resource'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: 1
        required: true
        schema:
          type: integer
