name: Run all tests
on: push

jobs:
  run-tests:
    name: Install and run tests
    runs-on: ubuntu-latest
    container: 
        image: composer:latest
        volumes:
          - ${{ github.workspace }}/:/app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
      - name: Run tests
        run: ./vendor/bin/pest
